### ISSUE TITLE
Selecting window from alt+tab (swapper)

### ISSUE THREAD

**Issue by ziombo** [urob/zmk-config#12]
How are you selecting a window with the current swapper implementation? Once I go into alt+tab mode, it requires me to send another key input to select a window, but the keypress affects selected window. 

For example if I'm switching between windows and press enter while selecting notepad, a new line will be inserted.

**Comment by urob** [comment]
That doesn't sound right. Just releasing the Nav-key should focus the currently selected window. E.g., `hold Nav` -> `tap swapper once` -> `release Nav` will focus the previous window.

**Comment by ziombo** [comment]
Ah, this might explain it as I have swapper assigned to a key on my main layer so there's no holding Nav
