### ISSUE TITLE
360 build

### ISSUE THREAD

**Issue by tjallemaal** [urob/zmk-config#14]
I'm a total noob, I have no clue how to build the firmware. 
Watched some tutorials so I have an idea, 
but how do I build firmware actually?
I want to build for the 360 pro but there are also other files for other keyboards (planck etc.) and this is already too much to process for my brain ...

**Comment by urob** [comment]
You only need to build the 360 file and can ignore the rest. Some of the other files will get called automatically when building but as long as they are in the repo you don't need to do anything. The easiest way to build is to use Github Actions and download the compiled firmware from the Github Actions tab.

If you are only building for the 360, you could also start with this repo https://github.com/urob/adv360-demo-config, which is less complex.

**Comment by tjallemaal** [comment]
Thanks alot!

**Comment by tjallemaal** [comment]
I'm sorry to ask this, but how exactly do I build the `adv360pro.keymap` file only?
Do I have to move it into a separate directory? because with the main branch in `actions` I cannot select that file specifically

**Comment by urob** [comment]
You can configure which boards are build with GitHub Actions in this file: https://github.com/urob/zmk-config/blob/main/build.yaml

Or you could just not care that it's building more boards and only download the firmware you need.

**Comment by tjallemaal** [comment]
thanks so much really. I must have done sth wrong beforehand, as when I built, I didnt get the firmware at all.
Now I have it and it is just a matter of picking the right file after the download, lol.

Don't know quite exactly what I missed but it's working now

cheers
