### ISSUE TITLE
no stroke recognition / flashing problem?

### ISSUE THREAD

**Issue by tjallemaal** [urob/zmk-config#15]
I think I successfully flashed the firmware, or so I thought.
My keyboard is being recognised but upon typing I don't see any output, alas. I'm wondering what could have gone wrong here

**Comment by urob** [comment]
It sounds like it isn't paired correctly. If you had it paired before and your previous build didn't have mouse-keys enabled, then you will need to re-set the pairing: 1. Forget bluetooth device on windows, 2. clear bluetooth connection on the 360, 3. re-pair

(This is necessary the first time you are enabling mouse keys, because the OS needs to change the driver from keyboard to keyboard + mouse)

**Comment by tjallemaal** [comment]
unfortunately, still not working.
I'm on MacOS Catalina fwiw

maybe for some reason, my OS doesnt get to do` the mouse + keyboard` driver thing?

**Comment by tjallemaal** [comment]
I just realised: it works when plugged in! it's a bluetooth thing.

**Comment by urob** [comment]
Another thing you could try if you haven't gotten Bluetooth to work yet:

https://zmk.dev/blog/2023/04/06/zephyr-3-2#known-issues

Afaik the official Kinesis firmware is still running on zephyr 3.0. That's why this steps may gut be necessary

**Comment by tjallemaal** [comment]
Oh! you just made me realise: when trying to BT_CLR I pressed the default 360-macro being `mod + gui`.

So when thinking of reset, I actually did not.

...
But I don't actually know how to access the `sys` layer yet.
How would that work?

**Comment by urob** [comment]
I have leds disabled in my main branch. For the layout see the image in the readme.

**Comment by tjallemaal** [comment]
I still don't get it :/ 

There is this line of code `#define _BT_SEL_KEYS_ &bt BT_SEL 0 &bt BT_SEL 1 &bt BT_SEL 2 &bt BT_SEL 3 &bt BT_CLR
`

I know to Fn+Num and then the BT key. But what do I do to cycle to `BT_CLR`?
Sorry, I really am kinda retarded

<img width="984" alt="Screenshot 2023-06-30 at 17 06 52" src="https://github.com/urob/zmk-config/assets/69585777/cb8a10d3-7458-47da-95fa-4eefcea2223f">

**Comment by urob** [comment]
> I still don't get it :/ 
> 
> 
> 
> There is this line of code `#define _BT_SEL_KEYS_ &bt BT_SEL 0 &bt BT_SEL 1 &bt BT_SEL 2 &bt BT_SEL 3 &bt BT_CLR
> 
> `
> 
> 
> 
> I know to Fn+Num and then the BT key. But what do I do to cycle to `BT_CLR`?
> 
> Sorry, I really am kinda retarded
> 
> 
> 
> <img width="984" alt="Screenshot 2023-06-30 at 17 06 52" src="https://github.com/urob/zmk-config/assets/69585777/cb8a10d3-7458-47da-95fa-4eefcea2223f">
> 
> 
> 
> 

_BT_SEL_KEYS_ expands to the definition above. So BT_CLR is on the inner index position in that row.

**Comment by tjallemaal** [comment]
> _BT_SEL_KEYS_ expands to the definition above. So BT_CLR is on the inner index position in that row.

What exactly do you mean by that? 
Could you possibly give an example where for example BT_2 is being cleared? I pressed the BT_SEL key and the key right to that simultaneously but I failed once again ...
