### ISSUE TITLE
Turning on LEDs

### ISSUE THREAD

**Issue by tjallemaal** [urob/zmk-config#17]
I came to know that LEDs are turned off. How can I enable that?

Thanks :)

**Comment by urob** [comment]
Led isn't officially supported by zmk and it isn't clear how well it combines with some of the other features used in this branch. If you want to give it a shot, there's a bit of guidance further down this issue:

https://github.com/urob/zmk-config/issues/1

Make sure to also read the very end of the issue on how to resolve compatibility issues with the 3.2 zephyr branch.
